# test this goreleaser config with:
# - cd cloud-connector
# - goreleaser --clean --snapshot --config .goreleaser.yml
version: 2
project_name: outsystemscc
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux       
dockers: 
  - image_templates: 
    - "ghcr.io/outsystems/{{ .ProjectName }}:{{ .Version }}"
    - "ghcr.io/outsystems/{{ .ProjectName }}:latest"
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title=OutSystems Cloud Connector
    - --label=org.opencontainers.image.description=OutSystems Cloud Connector
    - --label=org.opencontainers.image.url=https://github.com/outsystems/cloud-connector
    - --label=org.opencontainers.image.source=https://github.com/outsystems/cloud-connector
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
