name: sdlc_snyk_container_analysis

on:
    pull_request:
      types: [opened, synchronize, reopened]
      branches: [main] 

jobs:
    wait-for-pr-ci:
        uses: OutSystems/sdlc-gha-snyk/.github/workflows/wait-for-pr-check.yml@v1
        secrets: inherit
        with:
            commitSha: ${{ github.event.pull_request.head.sha }}
            runnerName: wait-for-pr-ci
            checkName: SDLC.TestNotes.Provider.Service-PR # YOU NEED TO EDIT THIS
            
    call-sdlc-snyk-container:
        needs: wait-for-pr-ci
        uses: OutSystems/sdlc-gha-snyk/.github/workflows/snyk-container.yml@v1.4.2 #This is in a non-blokcing mode
        secrets: inherit
        with:
            serviceName: "outsystems-sdlc-testnotes-service" # YOU NEED TO EDIT THIS
            commitSha: ${{ github.event.pull_request.head.sha }}
            dockerFilePath: Dockerfile # YOU (MAY) NEED TO EDIT THIS
    call-sdlc-snyk-container-ct:
        needs: wait-for-pr-ci
        uses: OutSystems/sdlc-gha-snyk/.github/workflows/snyk-container.yml@v1.4.2 #This is in a non-blokcing mode
        secrets: inherit
        with:
            serviceName: "outsystems-sdlc-testnotes-service-ct" # YOU NEED TO EDIT THIS
            commitSha: ${{ github.event.pull_request.head.sha }}
            dockerFilePath: Dockerfile # YOU (MAY) NEED TO EDIT THIS